# Generated by Django 3.2.2 on 2021-05-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe_info',
            fields=[
                ('recipe_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='', max_length=50)),
                ('titles', models.CharField(default='', max_length=200)),
                ('comment', models.TextField(default='')),
                ('images', models.CharField(default='', max_length=200)),
                ('serves', models.CharField(default='', max_length=50)),
                ('cooking', models.CharField(default='', max_length=50)),
                ('recipes', models.TextField(default='')),
                ('ingredients', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.IntegerField(default=0, unique=True)),
                ('clean_words', models.TextField()),
            ],
        ),
    ]
